### ISSUE TITLE
Bug in FindCommandParser

### ISSUE THREAD

**Issue by lungsin** [CS2103-AY1819S2-T12-2/main#41]
In FindCommandParserTest, there is an ignored test `parse_validArgs_returnsFindCommand()`.  Before we changed the implementation of FindCommandParser, it used to pass the test but now it failed. 

I've fixed some of the bugs in #40. Now, travis is still complaining, but in my local it works fine.

**Comment by sergiovieri** [comment]
@lungsin is this fixed?

**Comment by lucatriglia** [comment]
Hello, should be fixed in my latest PR
